### ISSUE TITLE
Update HED summary tool documentation

### ISSUE THREAD

**Issue by dungscout96** [hed-standard/hed-examples#241]
The "Example JSON remodeling file for a column value summary." in https://www.hed-resources.org/en/develop/HedSummaryGuide.html should also include "sample" in the `skip_columns` list

**Comment by VisLab** [comment]
Dung,
The paragraph above does say that sample should be skipped.  The problem
here is that sample isn't a column in the example dataset.
The link to the later example does have it in.  Do you still think it
should be put in?
Thanks,
Kay
