### ISSUE TITLE
How to handle trial context tags

### ISSUE THREAD

**Issue by dungscout96** [hed-standard/hed-examples#365]
From the case of annotating Arno's simple Oddball experiment:
```
"standard": "Sensory-event, Auditory-presentation, Non-target, Pitch/500 Hz, Duration/60 ms",
"oddball_with_reponse": "Sensory-event, Auditory-presentation, Oddball, Target, Pitch/1000 Hz, Participant-response, Correct-action",
"response": "Agent-action, Participant-response, (Press, Keyboard-key)",
```
How to best encode task-related trial information for an event instance? This issue occurred in Monique's stop-go task and seemingly most fMRI data cases as well.

Some current suggestions:
1. Add trial related behavior tags in (Behavioral-evidence, xxxxx) tag group
2. Introduce Trial-context tags and put trial-related actions tags in (Trial-context, xxxxxxx) tag group
3. Introduce a task description language. Users code the task logic and trial-related tags are added on demand as program evaluate the task logic on current event file.

Current reservations:
- For 1. and 2.: these are not intuitive tags. Users might not necessarily think about them as they first approach tagging. How to best guide users and sanity check annotations before they're published with the dataset?
- For 3.: ease of use is a concern, hard to get adoption otherwise.

**Comment by VisLab** [comment]
The most straightforward way of handling this is to introduce a trial column in the events file containing the trial number for each event.  Care must be taken to avoid incorporating this tag at the top level to avoid triggering a duplicate tag error.  This can be easily accomplished by using parentheses (perhaps in conjunction with curly braces if in a sidecar).

Ex:    `(Sensory-event, Visual-presentation, Image, Trial/1), (Sensory-event, Auditory-presentation, Beep, Trial/1)`

not   `Sensory-event, Visual-presentation, Image, Trial/1, Sensory-event, Auditory-presentation, Beep, Trial/1`

@dungscout96 does this resolve the issue?  Do you have a suggestion for a place to put a tutorial example in the HED resources?

**Comment by VisLab** [comment]
This issue has been transferred to hed-examples as a reminder to add a tutorial example.
